version: "3"

# You can't run all services at the same time

services:
  web:
    image: nginx:alpine
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80

  jenkins:
    image: 'jenkins/jenkins:alpine'
    restart: always
    ports:
      - '80:8080'
    volumes:
      - jenkins_data:/var

volumes:
  jenkins_data:
